services:
  postgres:
    container_name: weather_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: weather
    ports:
      - "5432:5432"