server:
  port: 8080
spring:
  application:
    name: WeatherTelegramBot

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  jpa:
    generate-ddl: false
    open-in-view: true
    hibernate:
      ddl-auto: none

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

url:
  api: ${API}

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

mailing:
  interval: PT01H